import Head from "next/head";
import { GetServerSideProps } from "next";

import { useEffect, useState } from "react";
import { SearchBar } from "@/components/SearchBar";
import ProjectCard from "@/components/ProjectCard/ProjectCard";
import { getAllProducts } from "@/services/api";
import { Product } from "@/types/Product";
import { getRecentSearch } from "@/services/search/api";

interface HomeProps {
  products: Product[];
  searchSuggestion: string[];
}

const Home: React.FC<HomeProps> = ({ products, searchSuggestion }) => {
  const [productList, setProductList] = useState<Product[]>(products);

  useEffect(() => {
    setProductList(products);
  }, [products]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <SearchBar searchSuggestion={searchSuggestion} />
        <main style={{ margin: "0 20px" }}>
          <h1 style={{ margin: "2rem 0" }}>Find your favorite products now.</h1>
          <div
            style={{
              display: "flex",
              columnGap: "1rem",
              rowGap: "1rem",
              flexWrap: "wrap",
            }}
          >
            {productList.map((p) => (
              <ProjectCard key={p.id} product={p} />
            ))}
          </div>
        </main>
      </div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  try {
    const products = await getAllProducts();
    console.log("products: ", products.length);
    const searchSuggestion = await getRecentSearch("");
    if (Array.isArray(products) && products.length) {
      return {
        props: {
          products,
          searchSuggestion,
        },
      };
    }

    return {
      props: {
        products: [],
        searchSuggestion: [],
      },
    };
  } catch (error) {
    console.log("error: ", error);
    return {
      props: {
        products: [],
        searchSuggestion: [],
      },
    };
  }
};
export default Home;
