import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { SearchBar } from "@/components/SearchBar";
import ProjectCard from "@/components/ProjectCard/ProjectCard";
import RecentSearches from "@/components/RecentSearches/RecentSearches";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <SearchBar />
        <main style={{ margin: "0 20px" }}>
          <RecentSearches />
          <h1>Find your favorite products now.</h1>
          <ProjectCard />
          <ProjectCard />
          <ProjectCard />
          <ProjectCard />
          <ProjectCard />
          <ProjectCard />
          <ProjectCard />
        </main>
      </div>
    </>
  );
}
