import { useEffect, useState } from "react";
import { GetServerSideProps } from "next";
import Head from "next/head";

import { ProjectCard, SearchBar } from "@/components";
import { getAllProducts } from "@/services/api";
import { Product } from "@/types/Product";
import { getRecentSearch } from "@/services/search/api";

interface HomeProps {
  products: Product[];
}

const Home: React.FC<HomeProps> = ({ products }) => {
  const [productList, setProductList] = useState<Product[]>(products);

  useEffect(() => {
    setProductList(products);
  }, [products]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <SearchBar />
        <main style={{ margin: "0 20px" }}>
          <h1 style={{ margin: "20px 0 2rem 0" }}>
            Find your favorite products now.
          </h1>
          <div style={{ display: "flex", marginBottom: 28 }}>
            <p className="category-link active">Trandy Foods</p>
            <p className="category-link">Bread</p>
            <p className="category-link">Milk</p>
            <p className="category-link">Egg</p>
          </div>
          <div
            style={{
              display: "flex",
              columnGap: "1rem",
              rowGap: "1rem",
              flexWrap: "wrap",
            }}
          >
            {productList.map((p) => (
              <ProjectCard key={p.id} product={p} />
            ))}
          </div>
        </main>
      </div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  try {
    const products = await getAllProducts();
    if (Array.isArray(products) && products.length) {
      return {
        props: {
          products,
        },
      };
    }

    return {
      props: {
        products: [],
      },
    };
  } catch (error) {
    console.log("error: ", error);
    return {
      props: {
        products: [],
      },
    };
  }
};
export default Home;
